import sys

def error(*msg):
    print('ERROR:', *msg)
    sys.exit(1)
